parameters:
    # Adds a fallback VARNISH_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(VARNISH_URL): ''

api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: Hello API Platform
    version: 1.0.0
    # Varnish integration, remove if unwanted
    http_cache:
        invalidation:
            enabled: true
            varnish_urls: ['%env(VARNISH_URL)%']
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization']
        public: true
    # Mercure integration, remove if unwanted
    mercure:
        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'
    
    collection:
        pagination:
            page_parameter_name: _page
            items_per_page: 10

    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header

    oauth:
        # To enable or disable oauth.
        enabled: false

        # The oauth client id.
        clientId: '149026378290-l1qmqto29bpnegc9263j4uto0kkuorsd.apps.googleusercontent.com'

        # The oauth client secret.
        clientSecret: 'hxoKewQWgPwZCarYRmBJGC_f'

        # The oauth type.
        type: 'oauth2'

        # The oauth flow grant type.
        flow: 'application'

        # The oauth token url.
        tokenUrl: 'https://accounts.google.com/o/oauth2/token'

        # The oauth authentication url.
        authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'

        # The oauth scopes.
        scopes: []
